version: "3.8"
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: '1111'
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: '1111'
      MYSQL_ROOT_PASSWORD: '1111'
      MYSQL_DATABASE: wp
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
volumes:
  wordpress:
  db:
    
